use std::fs::{self, File};
use std::io::{self, Read, Write};
use std::path::Path;

pub fn cli_input() {
    println!("[User IO]: Input Output");
    let mut usr_input = String::new();
    println!("Enter Something:");
    io::stdin()
        .read_line(&mut usr_input)
        // &mut used to borrow as mutable reference
        .expect("Failed to read input");
    // expect() is for to send a panic message if something goes wrong
    println!("You entered: {}", usr_input.trim());

    usr_input.clear();
    // Make sure that variable that will be passed to read_line functions,
    // has to be empty or it will appeend with the previous value of that variable

    println!("Enter integer");
    io::stdin()
        .read_line(&mut usr_input)
        .expect("Failed to read input");
    let int_num = usr_input.trim().parse::<i32>();
    // match is used to handle success and error by coders will
    match int_num {
        Ok(num) => println!("You entered: {}", num),
        Err(_err) => println!("Can't parse integer: {}", _err),
    }
}

pub fn file_io() {
    println!("[File IO]:");

    // Wriitng into File
    let contents = "This file is generated by \n\
    _14_io.rs";

    let dir_path = Path::new("temp/test");
    let file_path = dir_path.join("temp.txt");
    // Had to create directory separately because of Explicit Control of Rust
    fs::create_dir_all(dir_path).expect("Failed to create directory");

    // Creating File within existing directory
    let mut file_input = File::create(&file_path).expect("Failed to create file"); // &file_path to borrow so that we can use this later
    match file_input.write_all(contents.as_bytes()) {
        Ok(_) => println!("File Input Success"),
        Err(e) => println!("{}", e),
    };

    // Reading From File

    let mut file_contents = String::new();
    let mut file_output = File::open(&file_path).expect("Can't open file for reading");

    file_output.read_to_string(&mut file_contents).expect("msg");
    println!(
        "File Contents: \n////////////\n{}\n//////////",
        file_contents
    );
}
